name: ACI-WorkflowContainer-Stage
on:
  pull_request:
    types: [closed] 
    branches:
      - main 
jobs:
   extract-version:
    runs-on: ubuntu-latest
    outputs:
      sdk_version: ${{ steps.extract.outputs.sdk_version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract SDK version
        id: extract
		    run: |
         sdk_version=$(cat version.txt | grep -oP 'SDK_\d+\.\d+\.\d+')
         echo "sdk_version=$sdk_version" >> $GITHUB_ENV

      
        
   trigger-next-workflow:
    needs: extract-version
    runs-on: ubuntu-latest
    steps:
      - name: Trigger WF-SnoSki-SWRE-Stage
        run: |
          gh workflow run WF-SnoSki-SWRE-Stage.yml \
          --ref main \
          -f sdk_version=${{ needs.extract-version.outputs.sdk_version }}
  
        
