name: ACI-WorkflowContainer-Stage
on:
  pull_request:
    types: [closed]

jobs:
  versioning:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Get current version
        id: version
        run: echo "VERSION=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      - name: Trigger next workflow with version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X POST \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Content-Type: application/json" \
            --data '{"ref": "main", "inputs": {"version": "${{ env.VERSION }}"}}' \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/WF-SnoSki-SWRE-Stage.yml/dispatches
