name: Greeting on variable day

on:
  workflow_dispatch:
    inputs:
      name:
        description: Name
        type: string
        default: PB
      
    

env:
  DAY_OF_WEEK: Wednesday

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello CloudEthix Team it's Wednesday"
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
        env:
          First_Name: CloudEthix
