name: Labeler

on: [pull_request,workflow_dispatch]
  

jobs:
  label:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/labeler@v5
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        sync-labels: true
        configuration-path: .github/workflows/label.yml
        dot: true
