name: Labeler

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  workflow_dispatch:


jobs:
  label:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/labeler@v5
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        sync-labels: true
        configuration-path: .github/label.yml
        dot: true
