####version1####
####version2####
name: Initial Workflow
run-name: Deploy to Stage by @${{ github.actor }}
on:
  push:
    branches: 
     - dev
  pull_request:
    branches:
     -dev
  workflow_dispatch:

jobs:
  run_test_cases:
   runs-on: self-hosted
   steps:
     - uses: actions/checkout@v2
     - name: Run Test Cases
       run: | 
        echo "Running Test Cases"
        #npm ci
        #npm run test
        echo "Test cases Executed"
       shell: bash
    
      
     #- name: Version  
      # id: version  
      # uses: juliansangillo/tag-version@v1  
      # with:  
      #  production-branch: master    
        
  end:
    runs-on: ubuntu-latest
    steps: 
     - name: end
       run: echo "End Initial Workflow"
       shell: bash
    
  
