#v1

#v2

name: ACI-WorkflowContainer-Stage
run-name: Deploy to Stage by @${{ github.actor }}
on:

  #push:
   # branches: 
    # - dev
  pull_request:
    types: closed
  workflow_dispatch:
permissions:
  pull-requests: write  

jobs:
  run_test_cases:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2
     - name: Run Test Cases
       run: | 
        echo "Running Test Cases"
        #npm ci
        #npm run test
        echo "Test cases Executed"
       shell: bash
    
      
     #- name: Version  
      # id: version  
      # uses: juliansangillo/tag-version@v1  
      # with:  
      #  production-branch: master    
        
  end:
    runs-on: ubuntu-latest
    steps: 
     - name: end
       run: echo "End Initial Workflow"
       shell: bash

  label:
    runs-on: ubuntu-latest
    steps:
     - name: Set up Labeler
       uses: actions/labeler@v4
       with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          config-file: .github/labeler.yml
    
  
