name: Label PR's
on:
  pull_request:
    types:
      - opened
jobs:
  label_PRs :
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - run: gh pr edit "$NUMBER" --add-label "$LABELS"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.pullrequests.number }}
          LABELS: SDK_1.2.5 
